spring:
  datasource:
    url: jdbc:log4jdbc:sqlserver://172.31.55.40:1433;DatabaseName=DY_MES;encrypt=true;trustServerCertificate=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: MES_DEV
    password: okeT#(839Rb4
  security:
    user:
      name: admin
      password: admin
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    non-blocking-redelivery: false
    close-timeout: 60
    send-timeout: 60
    packages:
      trust-all: true
    jms:
      template:
        receive-timeout: 6000
        default-destination: "mesTopic"
        subject: "DEV.KR.6000.MES.MESsvr.1"
        prefix-client-id: "DEV.KR.6000.MES.UI-"

  jwt:
    header: Authorization
    secret: bHNtZXNfMjAyM19wcm9qZWN0XzAxMjM0NTY3ODlfMDEyMzQ1Njc4OV8wMTIzNDU2Nzg5XzAxMjM0NTY3ODlfMDEyMzQ1Njc4OQ== # lsmes_2023_project_0123456789_0123456789_0123456789_0123456789_0123456789
    token-access-validity-in-seconds: 7200 # 2 Hour
    token-refresh-validity-in-seconds: 604800 # 1 Week
  cors:
    allowed-origins: 'http://localhost:8080,http://localhost:3000,http://ap.kfems.net:22288,http://localhost:22288,http://localhost:22286,http://localhost:22287,http://ap.kfems.net:22286,http://ap.kfems.net:22287,http://210.90.165.89:22288'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'authorization'
    allow-credentials: true
    max-age: 1800
    
#mybatis
mybatis:
  configuration:
    default-executor-type: reuse
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    use-generated-keys: true
    jdbc-type-for-null: varchar
  mapper-locations:
    - classpath*:mappers/**/*.xml