#공통적용 내용으로 반드시 채워주셔야 합니다.
spring:
  #log색상지정
  output:
    ansi:
      enabled: always
  #servlet 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  profiles:
    #프로파일(local:개발자 환경, dev:개발서버, prod:운영 택1, 향후 runtime argument로 넘어갈 예정)
    active: local
  jackson:
    deserialization:
      accept-single-value-as-array: true
  datasource:
    #url: jdbc:mariadb://ap.kfems.net:22285/ls?passwordCharacterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:log4jdbc:sqlserver://172.31.55.40:1433;DatabaseName=DY_MES;encrypt=true;trustServerCertificate=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: MES_DEV
    password: okeT#(839Rb4
    security:
      user:
        name: admin
        password: admin
    activemq:
      broker-url: tcp://127.0.0.1:61616
      user: admin
      password: admin
      in-memory: true
      non-blocking-redelivery: false
      close-timeout: 60
      send-timeout: 60
      packages:
        trust-all: true
      jms:
        template:
          receive-timeout: 6000
          default-destination: mesTopic
          subject: "PROD.KR.6000.MES.MESsvr.1"
          prefix-client-id: "PROD.KR.6000.MES.UI-"

  jwt:
    header: "Authorization"
    secret: bHNtZXNfMjAyM19wcm9qZWN0XzAxMjM0NTY3ODlfMDEyMzQ1Njc4OV8wMTIzNDU2Nzg5XzAxMjM0NTY3ODlfMDEyMzQ1Njc4OQ== # lsmes_2023_project_0123456789_0123456789_0123456789_0123456789_0123456789
#    token-access-validity-in-seconds: 7200 # 2 Hour
    token-access-validity-in-seconds: 84000 # 24 Hour <-- 개발기간동안 임시로 적용.
    token-refresh-validity-in-seconds: 604800 # 1 Week

  cors:
    allowed-origins: 'http://localhost:8080,http://localhost:3000,http://localhost:4000,http://localhost:32286,http://ap.kfems.net:22288,http://localhost:22288,http://localhost:22286,http://localhost:22287,http://ap.kfems.net:22286,http://ap.kfems.net:22287,http://210.90.165.89:22288'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'authorization'
    allow-credentials: true
    max-age: 1800

#로깅관련
logging:
  level:
    root: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  file:
    path: logs
    name: app

server:
  #port설정
  port: 8080
  error:
    #에러표시여부
    include-exception: false
    #handler path
    path: /error
    # 기본처리사용여부
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        http-only: true
    context-path: "/api"
#mybatis
mybatis:
  configuration:
    default-executor-type: reuse
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    use-generated-keys: true
    jdbc-type-for-null: varchar
  mapper-locations:
    - classpath*:mappers/**/*.xml

#이하 해당 프로젝트에서 profile별로 필요한 정보를 세팅한다.(default와 중복될 경우 override)
#DB외 SPRING과 관련된 직접적인 셋팅은 자제하고, 이 외 필요한 것들만 선언해서 사용한다. (t)
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 600000 #(10분)
      max-lifetime: 1800000 #(30분)
      connection-timeout: 15000

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 600000 #(10분)
      max-lifetime: 1800000 #(30분)
      connection-timeout: 15000

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 600000 #(10분)
      max-lifetime: 1800000 #(30분)
      connection-timeout: 15000

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000 #(10분)
      max-lifetime: 1800000 #(30분)
      connection-timeout: 15000

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: never
